#.DEFAULT_GOAL := generate #choose the default goal instead of it being the first one
.PHONY: all clean #tells make that these goals are not files but some other thing

all:
    @echo "This does nothing. See Makefile"

clean:
	@echo "Cleaning up..."
	rm -f *.mod
	rm -f *o
	rm -f *.exe
	rm -f *.out
